---
- name: Systemd units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Service run state
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    enabled: true
    state: started

- name: Service restart
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
