galaxy_info:
  author: Versatus Labs
  description: A node to provide blob storage for the Versatus network
  company: Versatus Labs

  issue_tracker_url: https://github.com/versatus/versatus/issues

  license: MIT

  min_ansible_version: "2.10"

  # TODO: change this depending on what we test against
  platforms:
    - name: Ubuntu
      versions:
        - "jammy"
        - "focal"

  galaxy_tags: ["versatus", "blockchain", "web3"]

dependencies:
  - role: versatus_common
    vars:
      service_name: versatus-storage
      service_user: versatus-storage
      service_executable: "files/versa-storage"
<<<<<<< Updated upstream
      service_args: "daemon"
=======
      service_args: "-c {{ versatus_dir }}/etc/versatus-services.json -s storage1 -t storage daemon"
>>>>>>> Stashed changes
