---
- name: Monitor node
  ansible.builtin.package:
    name: prometheus
    state: present

- name: Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: "0755"

- name: Prometheus config directories
  ansible.builtin.file:
    path: "/etc/prometheus/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "scrape_targets"
    - "scrape_targets/node"
    - "scrape_targets/versatus"
