---
# Make sure the default node exporter package isn't installed, as we'll use github binaries for each
- name: Existing node exporter
  ansible.builtin.package:
    name: prometheus-node-exporter
    state: absent
- name: Prometheus exporter directory
  ansible.builtin.file:
    path: "{{ exporter_dir }}"
    state: directory
    owner: root
    group: root
- name: Prometheus exporters
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ service.pkg_url }}"
    dest: "{{ exporter_dir }}"
    creates: "{{ exporter_dir }}/{{ service.name }}"
    extra_opts:
      - "--strip-components"
      - 1
    include:
      - "{{ service.pkg_name }}/{{ service.name }}"
  loop: "{{ exporters }}"
  loop_control:
    loop_var: service
  notify:
    - Systemd reload
    - Service run state
    
- name: Prometheus exporter systemd units
  ansible.builtin.template:
    src: "systemd-service.j2"
    dest: "{{ systemd_dir }}/{{ service.name }}.service"
  loop: "{{ exporters }}"
  loop_control:
    loop_var: service
  notify:
    - Systemd reload
    - Service run state


- name: Node scrape target
  ansible.builtin.template:
    src: "scrape_target.yml.j2"
    dest: "/etc/prometheus/scrape_targets/{{ service.name }}/{{ ansible_hostname }}.yml"
    owner: root
    group: root
    mode: "0755"
  delegate_to: "{{ prometheus_node }}"
  loop: "{{ exporters }}"
  loop_control:
    loop_var: service
  notify:
    - Prometheus reload
