---
# Check whether there's already an instance of the Prometheus node exporter deployed
- name: Existing node_exporter
  ansible.builtin.stat:
    path: /usr/bin/prometheus-node-exporter
  register: node_exporter

#- name: Include Prometheus node exporter
  #ansible.builtin.set_fact:
    #exporters: "{{ exporters + [ 'node_exporter' ] }}"
  #when: node_exporter.stat.exists == False

# TODO: we could probably actually download the right package and extract it for the binary...
- name: Prometheus exporter deployment 
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "{{ exporter_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "0755"
  loop: "{{ exporters }}"
  notify:
    - Systemd reload
    - Service run state

- name: Prometheus exporter systemd units
  ansible.builtin.template:
    src: "systemd-service.j2"
    dest: "{{ systemd_dir }}/{{ service.name }}.service"
  loop: "{{ exporters }}"
  loop_control:
    loop_var: service
  notify:
    - Systemd reload
    - Service run state


- name: Node scrape target
  ansible.builtin.template:
    src: "scrape_target.yml.j2"
    dest: "/etc/prometheus/scrape_targets/node/{{ ansible_hostname }}.yml"
    owner: root
    group: root
    mode: "0755"
  delegate_to: "{{ prometheus_node }}"
